declare module 'styled-system' {
  export const space
  export const width
  export const fontSize
  export const color
  export const textAlign
  export const fontWeight
  export const alignItems
  export const justifyContent
  export const flexWrap
  export const flexDirection
  export const flex
  export const alignSelf
  export const borderRadius
  export const borderColor
  export const borderWidth
  export const boxShadow
  export const hover
  export const focus
  export const active
  export const disabled
  export const theme
  export const propTypes
  export const cleanElement
  export const removeProps
  export const style
  export const responsiveStyle
  export const pseudoStyle
}
